move_group:
  ros__parameters:
    robot_description_planning:
      joint_limits:
        joint_1:
          has_velocity_limits: true
          max_velocity: 0.40317105721069
          has_acceleration_limits: true
          max_acceleration: 2.0943951023932
        joint_2:
          has_velocity_limits: true
          max_velocity:  0.392175482923126
          has_acceleration_limits: true
          max_acceleration: 2.0943951023932
        joint_3:
          has_velocity_limits: true
          max_velocity: 0.725707902979242
          has_acceleration_limits: true
          max_acceleration: 3.49065850398866
        joint_4:
          has_velocity_limits: true
          max_velocity: 0.739146938219599
          has_acceleration_limits: true
          max_acceleration: 4.71238898038469
        joint_5:
          has_velocity_limits: true
          max_velocity: 0.739146938219599
          has_acceleration_limits: true
          max_acceleration: 4.71238898038469
        joint_6:
          has_velocity_limits: true
          max_velocity: 1.1093312725676
          has_acceleration_limits: true
          max_acceleration: 6.98131700797732
